### ISSUE TITLE
Code Release in Pytorch/Tensorflow

### ISSUE THREAD

**Issue by avisekiit** [piergiaj/latent-subevents#4]
Hi,

Congrats on the awesome paper and thanks for releasing the code. Do you have any plan to release the code in Pytorch or Tensorflow.

Thanks,
Avisek
Computer Vision Lab
Indian Institute of Technology Kharagpur

**Comment by piergiaj** [comment]
There is a newer and better performing version of this approach available in pytorch here:
https://github.com/piergiaj/tgm-icml19

**Comment by avisekiit** [comment]
Hi,
Thanks for the reply and for pointing out your new paper.
Will definitely try that out!!
